[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT & celery -A app.core.celery_app worker --loglevel=info"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
