"""Add resumo_contexto e citacoes_json to Pessoa

Revision ID: 2597a16c7649
Revises: ef987c8ff4dc
Create Date: 2026-03-09 13:55:05.912195
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = '2597a16c7649'
down_revision: Union[str, None] = 'ef987c8ff4dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pessoas', sa.Column('resumo_contexto', sa.Text(), nullable=True))
    op.add_column('pessoas', sa.Column('citacoes_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pessoas', 'citacoes_json')
    op.drop_column('pessoas', 'resumo_contexto')
    # ### end Alembic commands ###
