"""Add resumo_cache model for sprint 5

Revision ID: 3e88968b3ce2
Revises: 867dcc97d055
Create Date: 2026-03-09 11:08:51.594243
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '3e88968b3ce2'
down_revision: Union[str, None] = '867dcc97d055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumos_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inquerito_id', sa.UUID(), nullable=False),
    sa.Column('nivel', sa.String(length=20), nullable=False),
    sa.Column('referencia_id', sa.UUID(), nullable=True),
    sa.Column('texto_resumo', sa.Text(), nullable=False),
    sa.Column('modelo_llm', sa.String(length=100), nullable=True),
    sa.Column('tokens_usados', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inquerito_id'], ['inqueritos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumos_cache_inquerito_id'), 'resumos_cache', ['inquerito_id'], unique=False)
    op.create_index(op.f('ix_resumos_cache_referencia_id'), 'resumos_cache', ['referencia_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resumos_cache_referencia_id'), table_name='resumos_cache')
    op.drop_index(op.f('ix_resumos_cache_inquerito_id'), table_name='resumos_cache')
    op.drop_table('resumos_cache')
    # ### end Alembic commands ###
