"""Add resultado_agente model for sprint 6

Revision ID: 579595c7c041
Revises: 3e88968b3ce2
Create Date: 2026-03-09 11:30:11.789871
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = '579595c7c041'
down_revision: Union[str, None] = '3e88968b3ce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resultados_agentes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inquerito_id', sa.UUID(), nullable=False),
    sa.Column('tipo_agente', sa.String(length=30), nullable=False),
    sa.Column('referencia_id', sa.UUID(), nullable=True),
    sa.Column('resultado_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('texto_gerado', sa.Text(), nullable=True),
    sa.Column('modelo_llm', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inquerito_id'], ['inqueritos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resultados_agentes_inquerito_id'), 'resultados_agentes', ['inquerito_id'], unique=False)
    op.create_index(op.f('ix_resultados_agentes_referencia_id'), 'resultados_agentes', ['referencia_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resultados_agentes_referencia_id'), table_name='resultados_agentes')
    op.drop_index(op.f('ix_resultados_agentes_inquerito_id'), table_name='resultados_agentes')
    op.drop_table('resultados_agentes')
    # ### end Alembic commands ###
