"""Add entity models for sprint 4

Revision ID: 867dcc97d055
Revises: 
Create Date: 2026-03-08 22:48:04.218438
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = '867dcc97d055'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inqueritos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('numero', sa.String(length=100), nullable=False),
    sa.Column('delegacia', sa.String(length=200), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('estado_atual', sa.String(length=50), nullable=False),
    sa.Column('prioridade', sa.String(length=20), nullable=True),
    sa.Column('classificacao_estrategica', sa.String(length=50), nullable=True),
    sa.Column('total_paginas', sa.Integer(), nullable=False),
    sa.Column('total_documentos', sa.Integer(), nullable=False),
    sa.Column('modo_grande', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inqueritos_estado_atual'), 'inqueritos', ['estado_atual'], unique=False)
    op.create_index(op.f('ix_inqueritos_numero'), 'inqueritos', ['numero'], unique=False)
    op.create_table('documentos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inquerito_id', sa.UUID(), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=500), nullable=False),
    sa.Column('tipo_documento', sa.String(length=100), nullable=True),
    sa.Column('tipo_peca', sa.String(length=100), nullable=True),
    sa.Column('titulo_detectado', sa.String(length=500), nullable=True),
    sa.Column('hash_arquivo', sa.String(length=128), nullable=True),
    sa.Column('total_paginas', sa.Integer(), nullable=False),
    sa.Column('texto_extraido', sa.Text(), nullable=True),
    sa.Column('status_ocr', sa.String(length=30), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=True),
    sa.Column('status_processamento', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inquerito_id'], ['inqueritos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_inquerito_id'), 'documentos', ['inquerito_id'], unique=False)
    op.create_table('empresas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inquerito_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=300), nullable=False),
    sa.Column('tipo_empresa', sa.String(length=50), nullable=True),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inquerito_id'], ['inqueritos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresas_inquerito_id'), 'empresas', ['inquerito_id'], unique=False)
    op.create_table('pessoas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inquerito_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=300), nullable=False),
    sa.Column('tipo_pessoa', sa.String(length=50), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inquerito_id'], ['inqueritos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pessoas_inquerito_id'), 'pessoas', ['inquerito_id'], unique=False)
    op.create_table('sessoes_chat',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inquerito_id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=500), nullable=True),
    sa.Column('contexto', sa.String(length=50), nullable=True),
    sa.Column('total_mensagens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inquerito_id'], ['inqueritos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessoes_chat_inquerito_id'), 'sessoes_chat', ['inquerito_id'], unique=False)
    op.create_table('tarefas_agentes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inquerito_id', sa.UUID(), nullable=False),
    sa.Column('agente', sa.String(length=100), nullable=False),
    sa.Column('comando_usuario', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('modelo_utilizado', sa.String(length=100), nullable=True),
    sa.Column('custo_estimado', sa.Float(), nullable=True),
    sa.Column('tempo_execucao_ms', sa.Integer(), nullable=True),
    sa.Column('resultado_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inquerito_id'], ['inqueritos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tarefas_agentes_inquerito_id'), 'tarefas_agentes', ['inquerito_id'], unique=False)
    op.create_table('transicoes_estado',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inquerito_id', sa.UUID(), nullable=False),
    sa.Column('estado_anterior', sa.String(length=50), nullable=False),
    sa.Column('estado_novo', sa.String(length=50), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inquerito_id'], ['inqueritos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transicoes_estado_inquerito_id'), 'transicoes_estado', ['inquerito_id'], unique=False)
    op.create_table('volumes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inquerito_id', sa.UUID(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=500), nullable=True),
    sa.Column('total_paginas', sa.Integer(), nullable=False),
    sa.Column('resumo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inquerito_id'], ['inqueritos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_volumes_inquerito_id'), 'volumes', ['inquerito_id'], unique=False)
    op.create_table('auditorias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tarefa_id', sa.UUID(), nullable=False),
    sa.Column('tipo_auditoria', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('inconsistencias_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('aprovado_por_usuario', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tarefa_id'], ['tarefas_agentes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditorias_tarefa_id'), 'auditorias', ['tarefa_id'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inquerito_id', sa.UUID(), nullable=False),
    sa.Column('documento_id', sa.UUID(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('pagina_inicial', sa.Integer(), nullable=False),
    sa.Column('pagina_final', sa.Integer(), nullable=False),
    sa.Column('tipo_documento', sa.String(length=100), nullable=True),
    sa.Column('titulo_detectado', sa.String(length=500), nullable=True),
    sa.Column('pessoa_principal', sa.String(length=300), nullable=True),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('resumo_curto', sa.Text(), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('qdrant_point_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], ),
    sa.ForeignKeyConstraint(['inquerito_id'], ['inqueritos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunks_documento_id'), 'chunks', ['documento_id'], unique=False)
    op.create_index(op.f('ix_chunks_inquerito_id'), 'chunks', ['inquerito_id'], unique=False)
    op.create_table('contatos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inquerito_id', sa.UUID(), nullable=False),
    sa.Column('tipo_contato', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.String(length=255), nullable=False),
    sa.Column('pessoa_id', sa.UUID(), nullable=True),
    sa.Column('empresa_id', sa.UUID(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inquerito_id'], ['inqueritos.id'], ),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contatos_inquerito_id'), 'contatos', ['inquerito_id'], unique=False)
    op.create_table('enderecos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inquerito_id', sa.UUID(), nullable=False),
    sa.Column('endereco_completo', sa.Text(), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('pessoa_id', sa.UUID(), nullable=True),
    sa.Column('empresa_id', sa.UUID(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inquerito_id'], ['inqueritos.id'], ),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enderecos_inquerito_id'), 'enderecos', ['inquerito_id'], unique=False)
    op.create_table('eventos_cronologicos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inquerito_id', sa.UUID(), nullable=False),
    sa.Column('data_fato', sa.DateTime(), nullable=True),
    sa.Column('data_fato_str', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('documento_id', sa.UUID(), nullable=True),
    sa.Column('pagina_referencia', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inquerito_id'], ['inqueritos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_cronologicos_inquerito_id'), 'eventos_cronologicos', ['inquerito_id'], unique=False)
    op.create_table('logs_ingestao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('documento_id', sa.UUID(), nullable=False),
    sa.Column('inquerito_id', sa.UUID(), nullable=False),
    sa.Column('etapa', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('detalhes', sa.Text(), nullable=True),
    sa.Column('dados_extras', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duracao_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], ),
    sa.ForeignKeyConstraint(['inquerito_id'], ['inqueritos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_ingestao_documento_id'), 'logs_ingestao', ['documento_id'], unique=False)
    op.create_index(op.f('ix_logs_ingestao_inquerito_id'), 'logs_ingestao', ['inquerito_id'], unique=False)
    op.create_table('mensagens_chat',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sessao_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('fontes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('modelo_utilizado', sa.String(length=100), nullable=True),
    sa.Column('tokens_prompt', sa.Integer(), nullable=True),
    sa.Column('tokens_resposta', sa.Integer(), nullable=True),
    sa.Column('custo_estimado', sa.Float(), nullable=True),
    sa.Column('tempo_resposta_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sessao_id'], ['sessoes_chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensagens_chat_sessao_id'), 'mensagens_chat', ['sessao_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mensagens_chat_sessao_id'), table_name='mensagens_chat')
    op.drop_table('mensagens_chat')
    op.drop_index(op.f('ix_logs_ingestao_inquerito_id'), table_name='logs_ingestao')
    op.drop_index(op.f('ix_logs_ingestao_documento_id'), table_name='logs_ingestao')
    op.drop_table('logs_ingestao')
    op.drop_index(op.f('ix_eventos_cronologicos_inquerito_id'), table_name='eventos_cronologicos')
    op.drop_table('eventos_cronologicos')
    op.drop_index(op.f('ix_enderecos_inquerito_id'), table_name='enderecos')
    op.drop_table('enderecos')
    op.drop_index(op.f('ix_contatos_inquerito_id'), table_name='contatos')
    op.drop_table('contatos')
    op.drop_index(op.f('ix_chunks_inquerito_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_documento_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_auditorias_tarefa_id'), table_name='auditorias')
    op.drop_table('auditorias')
    op.drop_index(op.f('ix_volumes_inquerito_id'), table_name='volumes')
    op.drop_table('volumes')
    op.drop_index(op.f('ix_transicoes_estado_inquerito_id'), table_name='transicoes_estado')
    op.drop_table('transicoes_estado')
    op.drop_index(op.f('ix_tarefas_agentes_inquerito_id'), table_name='tarefas_agentes')
    op.drop_table('tarefas_agentes')
    op.drop_index(op.f('ix_sessoes_chat_inquerito_id'), table_name='sessoes_chat')
    op.drop_table('sessoes_chat')
    op.drop_index(op.f('ix_pessoas_inquerito_id'), table_name='pessoas')
    op.drop_table('pessoas')
    op.drop_index(op.f('ix_empresas_inquerito_id'), table_name='empresas')
    op.drop_table('empresas')
    op.drop_index(op.f('ix_documentos_inquerito_id'), table_name='documentos')
    op.drop_table('documentos')
    op.drop_index(op.f('ix_inqueritos_numero'), table_name='inqueritos')
    op.drop_index(op.f('ix_inqueritos_estado_atual'), table_name='inqueritos')
    op.drop_table('inqueritos')
    # ### end Alembic commands ###
