"""Add delegacia_origem and delegacia_atual to inquerito

Revision ID: ef987c8ff4dc
Revises: 579595c7c041
Create Date: 2026-03-09 13:32:37.299629
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'ef987c8ff4dc'
down_revision: Union[str, None] = '579595c7c041'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delegacias',
    sa.Column('codigo', sa.String(length=3), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('tipo', sa.Text(), nullable=True),
    sa.Column('municipio', sa.Text(), nullable=True),
    sa.Column('departamento', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.add_column('inqueritos', sa.Column('delegacia_origem_codigo', sa.String(length=10), nullable=True))
    op.add_column('inqueritos', sa.Column('delegacia_origem_nome', sa.String(length=200), nullable=True))
    op.add_column('inqueritos', sa.Column('delegacia_atual_codigo', sa.String(length=10), nullable=True))
    op.add_column('inqueritos', sa.Column('delegacia_atual_nome', sa.String(length=200), nullable=True))
    op.add_column('inqueritos', sa.Column('redistribuido', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inqueritos', 'redistribuido')
    op.drop_column('inqueritos', 'delegacia_atual_nome')
    op.drop_column('inqueritos', 'delegacia_atual_codigo')
    op.drop_column('inqueritos', 'delegacia_origem_nome')
    op.drop_column('inqueritos', 'delegacia_origem_codigo')
    op.drop_table('delegacias')
    # ### end Alembic commands ###
